{"updated_at": "2011-05-09T00:34:30Z", "repo": "rails", "created_at": "2011-05-09T00:34:30Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/1120717", "id": 1120717, "issue_url": "https://api.github.com/repos/rails/rails/issues/382", "issue_id": 382, "user": {"repos_url": "https://api.github.com/users/NZKoz/repos", "type": "User", "html_url": "https://github.com/NZKoz", "starred_url": "https://api.github.com/users/NZKoz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/NZKoz/subscriptions", "following_url": "https://api.github.com/users/NZKoz/following{/other_user}", "gravatar_id": "efa76b164a7de4a5730e4fa397cc4425", "organizations_url": "https://api.github.com/users/NZKoz/orgs", "url": "https://api.github.com/users/NZKoz", "gists_url": "https://api.github.com/users/NZKoz/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/efa76b164a7de4a5730e4fa397cc4425?d=https%3A%2F%2Fidenticons.github.com%2F85d8ce590ad8981ca2c8286f79f59954.png", "id": 197, "events_url": "https://api.github.com/users/NZKoz/events{/privacy}", "login": "NZKoz", "received_events_url": "https://api.github.com/users/NZKoz/received_events", "followers_url": "https://api.github.com/users/NZKoz/followers"}, "body": "`Thread#kill` and `Thread#raise` are basically impossible to use in a safe and reliable manner because the exceptions can come from anywhere and be of any type, Charles from jruby had a [great write up about it several years ago](http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html).  For example your particular patch won't help if the exception comes inside the `commit_db_transaction` method itself.\r\n\r\nI think attempting to be well behaved in the presence of `Thread#kill` is going to be too much effort to be worthwhile.\r\n", "_id": {"$oid": "52386109bd3543c1510122e7"}, "html_url": "https://github.com/rails/rails/pull/382#issuecomment-1120717"}
