{"updated_at": "2011-06-14T10:54:46Z", "repo": "rails", "created_at": "2011-06-14T10:48:27Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/1365183", "id": 1365183, "issue_url": "https://api.github.com/repos/rails/rails/issues/1622", "issue_id": 1622, "user": {"repos_url": "https://api.github.com/users/tardate/repos", "type": "User", "html_url": "https://github.com/tardate", "starred_url": "https://api.github.com/users/tardate/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tardate/subscriptions", "following_url": "https://api.github.com/users/tardate/following{/other_user}", "gravatar_id": "69f504d0e0c2c7d7b7215f488b028edd", "organizations_url": "https://api.github.com/users/tardate/orgs", "url": "https://api.github.com/users/tardate", "gists_url": "https://api.github.com/users/tardate/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/69f504d0e0c2c7d7b7215f488b028edd?d=https%3A%2F%2Fidenticons.github.com%2F812bfa6d29aa3c52e84258e9c2ab3d59.png", "id": 16432, "events_url": "https://api.github.com/users/tardate/events{/privacy}", "login": "tardate", "received_events_url": "https://api.github.com/users/tardate/received_events", "followers_url": "https://api.github.com/users/tardate/followers"}, "body": "@Roman2k thank you! as my attempts to fix this morphed I got mislead by the test. But now I discover that passing the block just gets me back to square one - $1 not available.\r\n\r\nSo this is not a fix .. yet. I might give it one more shot before giving up. I'll close this pull request till then", "_id": {"$oid": "52385287bd3543c151011868"}, "html_url": "https://github.com/rails/rails/pull/1622#issuecomment-1365183"}
