{"body": "@spastorino That seems to be in a different namespace. That raises `ActiveSupport::MessageEncryptor::InvalidMessage`, which is already defined. \r\n\r\n`InvalidMessage` error in the `MessageVerifier` namespace doesn't appear to be used anywhere.", "url": "https://api.github.com/repos/rails/rails/issues/comments/13712134", "created_at": "2013-02-18T09:03:52Z", "html_url": "https://github.com/rails/rails/pull/9302#issuecomment-13712134", "updated_at": "2013-02-18T09:03:52Z", "repo": "rails", "issue_id": 9302, "user": {"following_url": "https://api.github.com/users/felixclack/following{/other_user}", "events_url": "https://api.github.com/users/felixclack/events{/privacy}", "organizations_url": "https://api.github.com/users/felixclack/orgs", "url": "https://api.github.com/users/felixclack", "gists_url": "https://api.github.com/users/felixclack/gists{/gist_id}", "html_url": "https://github.com/felixclack", "subscriptions_url": "https://api.github.com/users/felixclack/subscriptions", "avatar_url": "https://2.gravatar.com/avatar/1abe821790c5a8516b6f5baafff5fa16?d=https%3A%2F%2Fidenticons.github.com%2F9f8684e630c4c30cad7b1f0935cd62ab.png", "repos_url": "https://api.github.com/users/felixclack/repos", "received_events_url": "https://api.github.com/users/felixclack/received_events", "gravatar_id": "1abe821790c5a8516b6f5baafff5fa16", "starred_url": "https://api.github.com/users/felixclack/starred{/owner}{/repo}", "login": "felixclack", "type": "User", "id": 3126, "followers_url": "https://api.github.com/users/felixclack/followers"}, "owner": "rails", "_id": {"$oid": "5237ead1bd3543c151009a74"}, "id": 13712134, "issue_url": "https://api.github.com/repos/rails/rails/issues/9302"}
