{"updated_at": "2013-02-18T09:03:52Z", "repo": "rails", "created_at": "2013-02-18T09:03:52Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/13712134", "id": 13712134, "issue_url": "https://api.github.com/repos/rails/rails/issues/9302", "issue_id": 9302, "user": {"repos_url": "https://api.github.com/users/felixclack/repos", "type": "User", "html_url": "https://github.com/felixclack", "starred_url": "https://api.github.com/users/felixclack/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/felixclack/subscriptions", "following_url": "https://api.github.com/users/felixclack/following{/other_user}", "gravatar_id": "1abe821790c5a8516b6f5baafff5fa16", "organizations_url": "https://api.github.com/users/felixclack/orgs", "url": "https://api.github.com/users/felixclack", "gists_url": "https://api.github.com/users/felixclack/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/1abe821790c5a8516b6f5baafff5fa16?d=https%3A%2F%2Fidenticons.github.com%2F9f8684e630c4c30cad7b1f0935cd62ab.png", "id": 3126, "events_url": "https://api.github.com/users/felixclack/events{/privacy}", "login": "felixclack", "received_events_url": "https://api.github.com/users/felixclack/received_events", "followers_url": "https://api.github.com/users/felixclack/followers"}, "body": "@spastorino That seems to be in a different namespace. That raises `ActiveSupport::MessageEncryptor::InvalidMessage`, which is already defined. \r\n\r\n`InvalidMessage` error in the `MessageVerifier` namespace doesn't appear to be used anywhere.", "_id": {"$oid": "5237ead1bd3543c151009a74"}, "html_url": "https://github.com/rails/rails/pull/9302#issuecomment-13712134"}
