{"updated_at": "2013-03-14T11:58:45Z", "repo": "rails", "created_at": "2013-03-14T11:58:30Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/14898574", "id": 14898574, "issue_url": "https://api.github.com/repos/rails/rails/issues/9717", "issue_id": 9717, "user": {"repos_url": "https://api.github.com/users/pftg/repos", "type": "User", "html_url": "https://github.com/pftg", "starred_url": "https://api.github.com/users/pftg/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pftg/subscriptions", "following_url": "https://api.github.com/users/pftg/following{/other_user}", "gravatar_id": "712a9cc852c438c0873ef0a98f749f2e", "organizations_url": "https://api.github.com/users/pftg/orgs", "url": "https://api.github.com/users/pftg", "gists_url": "https://api.github.com/users/pftg/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/712a9cc852c438c0873ef0a98f749f2e?d=https%3A%2F%2Fidenticons.github.com%2F58adcd3cfec4758f40b142a29c054d55.png", "id": 125715, "events_url": "https://api.github.com/users/pftg/events{/privacy}", "login": "pftg", "received_events_url": "https://api.github.com/users/pftg/received_events", "followers_url": "https://api.github.com/users/pftg/followers"}, "body": "If I add `validates_uniqueness_of` then record will be invalid: `ActiveRecord::RecordInvalid: Validation failed: ... has already been taken`.\r\n\r\nNext steps, I gonna to request feature to take in account `mark_for_destruction` in validation uniqueness and others constraints.\r\n\r\nElsewhere the destroy before insert was in versions before 3.2.7. And I reverted it.", "_id": {"$oid": "523d1037bd354364b90045e5"}, "html_url": "https://github.com/rails/rails/pull/9717#issuecomment-14898574"}
