{"updated_at": "2011-07-25T20:32:08Z", "repo": "rails", "created_at": "2011-07-25T20:32:08Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/1648895", "id": 1648895, "issue_url": "https://api.github.com/repos/rails/rails/issues/2227", "issue_id": 2227, "user": {"repos_url": "https://api.github.com/users/skippy/repos", "type": "User", "html_url": "https://github.com/skippy", "starred_url": "https://api.github.com/users/skippy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/skippy/subscriptions", "following_url": "https://api.github.com/users/skippy/following{/other_user}", "gravatar_id": "925b3c7354d16011fcb78895d2c6ceb3", "organizations_url": "https://api.github.com/users/skippy/orgs", "url": "https://api.github.com/users/skippy", "gists_url": "https://api.github.com/users/skippy/gists{/gist_id}", "avatar_url": "https://0.gravatar.com/avatar/925b3c7354d16011fcb78895d2c6ceb3?d=https%3A%2F%2Fidenticons.github.com%2Fe8542a04d734d0cae36d648b3f519e5c.png", "id": 3746, "events_url": "https://api.github.com/users/skippy/events{/privacy}", "login": "skippy", "received_events_url": "https://api.github.com/users/skippy/received_events", "followers_url": "https://api.github.com/users/skippy/followers"}, "body": "@pritchie, addressing the 3 points in order:\r\n\r\n* the query cache will not be turned on IF the original connection fails; otherwise it will be there.\r\n\r\n* The querycache was baked into the connection, it seems, to just keep things clean, and now to pull it out seems messy.  I made the change that I did to try and keep it small and focused rather than a (much) larger patch to decouple it completely from the connection.  But I also think that is the right approach rather than having dependencies on the middleware (or some helper class).  The other way to look at this is to not have ActiveRecord::Base.connection actually trigger a db call until used, but again, I think that is a thornier change outside of the scope\r\n\r\n* I looked at that, but the reason I kept it general is that the exceptions that are thrown are direct from the driver and are quite varied in type.  I'm not sure you can make the expectation that they all stem from StandardError", "_id": {"$oid": "52384649bd3543c151010ee3"}, "html_url": "https://github.com/rails/rails/pull/2227#issuecomment-1648895"}
