{"body": "I ran into this as well and spent two days tracking down the issue. For me I was using ActiveRecord outside of Rails, and doing a \r\n\r\n```ActiveRecord::Base.logger = Logger.new(STDERR)```\r\n\r\ngot me past the error, so now I'll just make sure we're actually handling logging in my app.", "url": "https://api.github.com/repos/rails/rails/issues/comments/3802086", "created_at": "2012-02-03T18:54:56Z", "html_url": "https://github.com/rails/rails/pull/3712#issuecomment-3802086", "updated_at": "2012-02-03T18:54:56Z", "repo": "rails", "issue_id": 3712, "user": {"following_url": "https://api.github.com/users/mkoby/following{/other_user}", "events_url": "https://api.github.com/users/mkoby/events{/privacy}", "organizations_url": "https://api.github.com/users/mkoby/orgs", "url": "https://api.github.com/users/mkoby", "gists_url": "https://api.github.com/users/mkoby/gists{/gist_id}", "html_url": "https://github.com/mkoby", "subscriptions_url": "https://api.github.com/users/mkoby/subscriptions", "avatar_url": "https://1.gravatar.com/avatar/814929addf7c2811ff5edb5b277e29db?d=https%3A%2F%2Fidenticons.github.com%2Fddd864f1589f422aa9df35fe6c40140d.png", "repos_url": "https://api.github.com/users/mkoby/repos", "received_events_url": "https://api.github.com/users/mkoby/received_events", "gravatar_id": "814929addf7c2811ff5edb5b277e29db", "starred_url": "https://api.github.com/users/mkoby/starred{/owner}{/repo}", "login": "mkoby", "type": "User", "id": 107053, "followers_url": "https://api.github.com/users/mkoby/followers"}, "owner": "rails", "_id": {"$oid": "523832c9bd3543c15100f90d"}, "id": 3802086, "issue_url": "https://api.github.com/repos/rails/rails/issues/3712"}
