{"updated_at": "2011-02-09T20:45:27Z", "repo": "rails", "created_at": "2011-02-09T20:45:27Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/755181", "id": 755181, "issue_url": "https://api.github.com/repos/rails/rails/issues/146", "issue_id": 146, "user": {"repos_url": "https://api.github.com/users/joshk/repos", "type": "User", "html_url": "https://github.com/joshk", "starred_url": "https://api.github.com/users/joshk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/joshk/subscriptions", "following_url": "https://api.github.com/users/joshk/following{/other_user}", "gravatar_id": "21b21efe14359ec323f9a70464b91e39", "organizations_url": "https://api.github.com/users/joshk/orgs", "url": "https://api.github.com/users/joshk", "gists_url": "https://api.github.com/users/joshk/gists{/gist_id}", "avatar_url": "https://0.gravatar.com/avatar/21b21efe14359ec323f9a70464b91e39?d=https%3A%2F%2Fidenticons.github.com%2F818cdcf067c824a4e34f9293de3b15a9.png", "id": 8701, "events_url": "https://api.github.com/users/joshk/events{/privacy}", "login": "joshk", "received_events_url": "https://api.github.com/users/joshk/received_events", "followers_url": "https://api.github.com/users/joshk/followers"}, "body": "Hey paneq,\r\n\r\nI tried to create a failing test case for this issue but I could not replicate the case.\r\n\r\nHere is the abstract of [my test](https://gist.github.com/818728).\r\n\r\nFrom my understanding you are overriding the destroy method in your class, doing some custom checks/logic, and then calling super so the original destroy runs? Please correct me if I am misunderstanding something.\r\n\r\nThanks,\r\n\r\nJosh\r\n\r\n", "_id": {"$oid": "5238672dbd3543c15101288b"}, "html_url": "https://github.com/rails/rails/pull/146#issuecomment-755181"}
