{"body": "Hey Ernie,\r\n\r\nThanks for the pull request. It would be great if you could add a test which actually does an outer join with a condition (presumably via `Foo.includes(...)`) that fails on current master.\r\n\r\nAlso, can you confirm this has been tested under postgres? I remember a problem to do with referencing joined tables on postgres (and oracle) where the you referenced table \"foo\" in an ON clause before \"foo\" is actually joined, which would cause an error. Might not be relevant here though.\r\n\r\nCheers", "url": "https://api.github.com/repos/rails/rails/issues/comments/1107208", "created_at": "2011-05-05T18:03:48Z", "html_url": "https://github.com/rails/rails/pull/399#issuecomment-1107208", "updated_at": "2011-05-05T18:03:48Z", "repo": "rails", "issue_id": 399, "user": {"following_url": "https://api.github.com/users/jonleighton/following{/other_user}", "events_url": "https://api.github.com/users/jonleighton/events{/privacy}", "organizations_url": "https://api.github.com/users/jonleighton/orgs", "url": "https://api.github.com/users/jonleighton", "gists_url": "https://api.github.com/users/jonleighton/gists{/gist_id}", "html_url": "https://github.com/jonleighton", "subscriptions_url": "https://api.github.com/users/jonleighton/subscriptions", "avatar_url": "https://2.gravatar.com/avatar/2940bc7d4506f3e099e3dcc32a412b98?d=https%3A%2F%2Fidenticons.github.com%2F798cebccb32617ad94123450fd137104.png", "repos_url": "https://api.github.com/users/jonleighton/repos", "received_events_url": "https://api.github.com/users/jonleighton/received_events", "gravatar_id": "2940bc7d4506f3e099e3dcc32a412b98", "starred_url": "https://api.github.com/users/jonleighton/starred{/owner}{/repo}", "login": "jonleighton", "type": "User", "id": 1979, "followers_url": "https://api.github.com/users/jonleighton/followers"}, "owner": "rails", "_id": {"$oid": "523860b8bd3543c1510122a9"}, "id": 1107208, "issue_url": "https://api.github.com/repos/rails/rails/issues/399"}
