{"updated_at": "2012-12-26T22:06:49Z", "repo": "rails", "created_at": "2012-12-26T22:02:52Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/11695303", "id": 11695303, "issue_url": "https://api.github.com/repos/rails/rails/issues/8624", "issue_id": 8624, "user": {"repos_url": "https://api.github.com/users/shime/repos", "type": "User", "html_url": "https://github.com/shime", "starred_url": "https://api.github.com/users/shime/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shime/subscriptions", "following_url": "https://api.github.com/users/shime/following{/other_user}", "gravatar_id": "076ddab874e5e370a451f0da52afb85c", "organizations_url": "https://api.github.com/users/shime/orgs", "url": "https://api.github.com/users/shime", "gists_url": "https://api.github.com/users/shime/gists{/gist_id}", "avatar_url": "https://1.gravatar.com/avatar/076ddab874e5e370a451f0da52afb85c?d=https%3A%2F%2Fidenticons.github.com%2F4dfcdf4942bab88a3d4ddeb3a68a01a4.png", "id": 703563, "events_url": "https://api.github.com/users/shime/events{/privacy}", "login": "shime", "received_events_url": "https://api.github.com/users/shime/received_events", "followers_url": "https://api.github.com/users/shime/followers"}, "body": "I'm trying to find out which exception occurred from the middleware. \r\n\r\nLet's say I have something like this:\r\n\r\n```ruby\r\nclass ExceptionDetector\r\n   def initialize(app)\r\n     @app = app\r\n   end\r\n\r\n   def call(env)\r\n      response = @app.call(env)\r\n      if env[\"action_dispatch.exception\"] # or whatever else\r\n        puts \"exception occurred\"\r\n      end\r\n      response\r\n   end\r\nend\r\n```\r\n\r\nAnd my middleware stack looks like\r\n```ruby\r\n\r\nuse ExceptionDetector\r\nuse ActionDispatch::ShowExceptions\r\nuse ActionDispatch::DebugExceptions\r\nrun Testola::Application.routes\r\n```\r\n\r\n\r\nIs there a better way to achieve this? Should I just add the rescue block inside my middleware and place it after exception middleware? Like this:\r\n\r\n```ruby\r\nclass ExceptionDetector\r\n   def initialize(app)\r\n      @app = app\r\n   end\r\n\r\n   def call(env)\r\n      begin\r\n        response = @app.call(env)\r\n      rescue => exception\r\n        puts \"exception occurred\"\r\n        raise exception\r\n      end\r\n      response\r\n   end\r\nend\r\n\r\n# stack:\r\n\r\nuse ActionDispatch::ShowExceptions\r\nuse ActionDispatch::DebugExceptions\r\nuse ExceptionDetector\r\nrun Testola::Application.routes\r\n\r\n```\r\n\r\nThanks!", "_id": {"$oid": "5237f18abd3543c15100a464"}, "html_url": "https://github.com/rails/rails/pull/8624#issuecomment-11695303"}
