{"body": "Right. Based on feedback from #6557, I started again putting test coverage on the re-connect behavior that was supposed to be fixed by #6477. It turned out that was not quite working right because of an incompatible change to ...::PostgteSQLAdapter#translate_exception, and there had been no test coverage to reveal this problem. ", "url": "https://api.github.com/repos/rails/rails/issues/comments/6181625", "created_at": "2012-06-07T17:05:45Z", "html_url": "https://github.com/rails/rails/pull/6654#issuecomment-6181625", "updated_at": "2012-06-07T17:05:45Z", "repo": "rails", "issue_id": 6654, "user": {"following_url": "https://api.github.com/users/stevecj/following{/other_user}", "events_url": "https://api.github.com/users/stevecj/events{/privacy}", "organizations_url": "https://api.github.com/users/stevecj/orgs", "url": "https://api.github.com/users/stevecj", "gists_url": "https://api.github.com/users/stevecj/gists{/gist_id}", "html_url": "https://github.com/stevecj", "subscriptions_url": "https://api.github.com/users/stevecj/subscriptions", "avatar_url": "https://1.gravatar.com/avatar/4f6079564f02b87e4c0989585439eb39?d=https%3A%2F%2Fidenticons.github.com%2F116eb226cf0b16d4f0bb6c09d94f74f5.png", "repos_url": "https://api.github.com/users/stevecj/repos", "received_events_url": "https://api.github.com/users/stevecj/received_events", "gravatar_id": "4f6079564f02b87e4c0989585439eb39", "starred_url": "https://api.github.com/users/stevecj/starred{/owner}{/repo}", "login": "stevecj", "type": "User", "id": 388671, "followers_url": "https://api.github.com/users/stevecj/followers"}, "owner": "rails", "_id": {"$oid": "523e346ebd354364b900e674"}, "id": 6181625, "issue_url": "https://api.github.com/repos/rails/rails/issues/6654"}
