{"body": "@senny is not better to fix this behavior inside `ExceptionWrapper`?", "url": "https://api.github.com/repos/rails/rails/issues/comments/8602228", "created_at": "2012-09-17T00:49:24Z", "html_url": "https://github.com/rails/rails/pull/7660#issuecomment-8602228", "updated_at": "2012-09-17T00:49:24Z", "repo": "rails", "issue_id": 7660, "user": {"following_url": "https://api.github.com/users/rafaelfranca/following{/other_user}", "events_url": "https://api.github.com/users/rafaelfranca/events{/privacy}", "organizations_url": "https://api.github.com/users/rafaelfranca/orgs", "url": "https://api.github.com/users/rafaelfranca", "gists_url": "https://api.github.com/users/rafaelfranca/gists{/gist_id}", "html_url": "https://github.com/rafaelfranca", "subscriptions_url": "https://api.github.com/users/rafaelfranca/subscriptions", "avatar_url": "https://1.gravatar.com/avatar/0525b332aafb83307b32d9747a93de03?d=https%3A%2F%2Fidenticons.github.com%2F2c7b84fa30f0cea96a90729afe2970a0.png", "repos_url": "https://api.github.com/users/rafaelfranca/repos", "received_events_url": "https://api.github.com/users/rafaelfranca/received_events", "gravatar_id": "0525b332aafb83307b32d9747a93de03", "starred_url": "https://api.github.com/users/rafaelfranca/starred{/owner}{/repo}", "login": "rafaelfranca", "type": "User", "id": 47848, "followers_url": "https://api.github.com/users/rafaelfranca/followers"}, "owner": "rails", "_id": {"$oid": "5237f94cbd3543c15100b417"}, "id": 8602228, "issue_url": "https://api.github.com/repos/rails/rails/issues/7660"}
